from __future__ import annotations

import re
from collections.abc import Iterable
from hashlib import sha256
from pathlib import Path

from pypdf import PdfReader

from acacium.integrity import verify_sha256
from acacium.schemas import (
    Evidence,
    ScoreBand,
    ScoringRubric,
    ScoringRule,
    ServiceCatalogue,
    Signal,
    SourceDocument,
)

_SENTENCE_BREAK = re.compile(r"(?<=[.!?])\s+|\n{2,}")


def extract_document(
    document: SourceDocument,
    documents_dir: Path,
    service_catalogue: ServiceCatalogue,
    scoring_rubric: ScoringRubric,
) -> list[Signal]:
    """Extract cautious, evidence-linked candidate signals from the declared report scope."""
    source_path = documents_dir / document.filename
    verify_sha256(source_path, document.sha256)
    reader = PdfReader(str(source_path))
    matches: list[Signal] = []

    for physical_page in range(
        document.scope.first_physical_page, document.scope.last_physical_page + 1
    ):
        page_text = reader.pages[physical_page - 1].extract_text() or ""
        for excerpt in _matching_excerpts(page_text, scoring_rubric):
            matches.append(
                _to_signal(document, physical_page, excerpt, service_catalogue, scoring_rubric)
            )

    return _deduplicate_and_rank(matches)


def _matching_excerpts(page_text: str, scoring_rubric: ScoringRubric) -> Iterable[str]:
    cleaned = re.sub(r"\s+", " ", page_text).strip()
    for sentence in _SENTENCE_BREAK.split(cleaned):
        sentence = sentence.strip()
        excerpt = sentence[:900]
        if len(excerpt) >= 35 and _is_substantive(excerpt, scoring_rubric):
            yield excerpt


def _is_substantive(sentence: str, scoring_rubric: ScoringRubric) -> bool:
    """Avoid treating generic governance mentions as commercial workforce evidence."""
    rule = _matching_rule(sentence, scoring_rubric)
    return rule is not None and any(
        match.casefold() in sentence.casefold() for match in rule.substantive_matches
    )


def _to_signal(
    document: SourceDocument,
    page: int,
    excerpt: str,
    service_catalogue: ServiceCatalogue,
    scoring_rubric: ScoringRubric,
) -> Signal:
    rule = _matching_rule(excerpt, scoring_rubric)
    if rule is None:
        raise ValueError("No configured scoring rule matches the extracted evidence.")
    band = _score_band(excerpt, rule)

    digest = sha256(f"{document.id}:{page}:{excerpt}".encode()).hexdigest()[:16]
    return Signal(
        id=f"sig-{digest}",
        organisation=document.organisation,
        category=rule.category,
        service=_service_name(excerpt, service_catalogue),
        source_fact=excerpt,
        interpretation=(
            "This is an evidence-led conversation hypothesis, not evidence of a procurement "
            "decision."
        ),
        reporting_period=document.scope.reporting_period,
        score=band.score,
        score_reasons=band.score_reasons,
        proposed_next_action=rule.proposed_next_action,
        evidence=Evidence(
            document_id=document.id,
            filename=document.filename,
            physical_page=page,
            excerpt=excerpt,
            scope_title=document.scope.title,
        ),
        caveats=[
            "Candidate generated by deterministic local extraction; reviewer approval is required."
        ],
    )


def _matching_rule(excerpt: str, scoring_rubric: ScoringRubric) -> ScoringRule | None:
    lowered = excerpt.casefold()
    return next(
        (
            rule
            for rule in scoring_rubric.rules
            if any(trigger.casefold() in lowered for trigger in rule.triggers)
        ),
        None,
    )


def _score_band(excerpt: str, rule: ScoringRule) -> ScoreBand:
    lowered = excerpt.casefold()
    return next(
        (
            band
            for band in rule.score_bands
            if not band.evidence_matches
            or any(match.casefold() in lowered for match in band.evidence_matches)
        ),
        rule.score_bands[-1],
    )


def _service_name(excerpt: str, service_catalogue: ServiceCatalogue) -> str:
    """Choose the most specific versioned service match for a source excerpt."""
    lowered = excerpt.casefold()
    candidates = [
        (
            sum(match.casefold() in lowered for match in service.matches),
            service.priority,
            service.name,
        )
        for service in service_catalogue.services
        if any(match.casefold() in lowered for match in service.matches)
    ]
    if not candidates:
        raise ValueError("No configured service matches the extracted evidence.")
    return max(candidates)[2]


def _deduplicate_and_rank(signals: list[Signal]) -> list[Signal]:
    unique: dict[tuple[str, str, int], Signal] = {}
    for signal in signals:
        key = (signal.organisation, signal.category, signal.evidence.physical_page)
        existing = unique.get(key)
        if existing is None or _evidence_quality(signal) > _evidence_quality(existing):
            unique[key] = signal
    return sorted(unique.values(), key=lambda signal: (-signal.score, signal.id))[:20]


def _evidence_quality(signal: Signal) -> tuple[int, int]:
    """Prefer a page's most measurable and decision-relevant excerpt."""
    excerpt = signal.source_fact.casefold()
    indicators = ("£", "wte", "vacan", "above cap", "expenditure", "exit plan")
    return sum(indicator in excerpt for indicator in indicators), len(signal.source_fact)
