from __future__ import annotations

import re
from collections.abc import Iterable
from hashlib import sha256
from pathlib import Path

from pypdf import PdfReader

from acacium.schemas import Evidence, Signal, SourceDocument

_KEYWORDS = re.compile(
    r"\b(agency|bank|vacan(?:cy|cies)|recruit(?:ment|ing)|headhunt(?:ing)?|WTE|staffing)\b",
    re.IGNORECASE,
)
_SENTENCE_BREAK = re.compile(r"(?<=[.!?])\s+|\n{2,}")
_TEMPORARY_STAFFING_CONTEXT = re.compile(
    r"(£|\b\d+(?:\.\d+)?\s*WTE\b|spend|cost|expenditure|above cap|exit plan|temporary staffing)",
    re.IGNORECASE,
)
_RECRUITMENT_CONTEXT = re.compile(
    r"(vacan|recruit|headhunt|locum|staffing shortfall|rota resilience)", re.IGNORECASE
)


def extract_document(document: SourceDocument, documents_dir: Path) -> list[Signal]:
    """Extract cautious, evidence-linked candidate signals from the declared report scope."""
    source_path = documents_dir / document.filename
    reader = PdfReader(str(source_path))
    matches: list[Signal] = []

    for physical_page in range(
        document.scope.first_physical_page, document.scope.last_physical_page + 1
    ):
        page_text = reader.pages[physical_page - 1].extract_text() or ""
        for excerpt in _matching_excerpts(page_text):
            matches.append(_to_signal(document, physical_page, excerpt))

    return _deduplicate_and_rank(matches)


def _matching_excerpts(page_text: str) -> Iterable[str]:
    cleaned = re.sub(r"\s+", " ", page_text).strip()
    for sentence in _SENTENCE_BREAK.split(cleaned):
        sentence = sentence.strip()
        if len(sentence) >= 35 and _KEYWORDS.search(sentence) and _is_substantive(sentence):
            yield sentence[:900]


def _is_substantive(sentence: str) -> bool:
    """Avoid treating generic governance mentions as commercial workforce evidence."""
    lowered = sentence.casefold()
    if "agency" in lowered or "bank" in lowered:
        return bool(_TEMPORARY_STAFFING_CONTEXT.search(sentence))
    return bool(_RECRUITMENT_CONTEXT.search(sentence))


def _to_signal(document: SourceDocument, page: int, excerpt: str) -> Signal:
    lowered = excerpt.lower()
    if "agency" in lowered or "bank" in lowered:
        category = "temporary-staff expenditure"
        service = "Managed staff bank / RPO"
        score = 92.5 if _TEMPORARY_STAFFING_CONTEXT.search(excerpt) else 77.5
        reasons = [
            "Clear workforce-service fit",
            "Explicit spend or staffing evidence",
            "Recent pack",
        ]
        action = "Validate the current temporary staffing position and explore bank optimisation."
    elif "recruit" in lowered or "headhunt" in lowered:
        category = "recruitment activity"
        service = "Permanent recruitment"
        score = 82.5
        reasons = [
            "Clear recruitment-service fit",
            "Specific workforce activity",
            "Evidence requires review",
        ]
        action = "Confirm whether the recruitment activity remains open before proposing support."
    else:
        category = "vacancy pressure"
        service = "Permanent recruitment"
        score = 67.5
        reasons = [
            "Specific workforce reference",
            "Period may be historical",
            "Human validation required",
        ]
        action = "Ask whether the documented gap remains unresolved before suggesting support."

    digest = sha256(f"{document.id}:{page}:{excerpt}".encode()).hexdigest()[:16]
    return Signal(
        id=f"sig-{digest}",
        organisation=document.organisation,
        category=category,
        service=service,
        source_fact=excerpt,
        interpretation=(
            "This is an evidence-led conversation hypothesis, not evidence of a procurement "
            "decision."
        ),
        reporting_period=document.scope.reporting_period,
        score=score,
        score_reasons=reasons,
        proposed_next_action=action,
        evidence=Evidence(
            document_id=document.id,
            filename=document.filename,
            physical_page=page,
            excerpt=excerpt,
            scope_title=document.scope.title,
        ),
        caveats=[
            "Candidate generated by deterministic local extraction; reviewer approval is required."
        ],
    )


def _deduplicate_and_rank(signals: list[Signal]) -> list[Signal]:
    unique: dict[tuple[str, str, int], Signal] = {}
    for signal in signals:
        key = (signal.organisation, signal.category, signal.evidence.physical_page)
        existing = unique.get(key)
        if existing is None or _evidence_quality(signal) > _evidence_quality(existing):
            unique[key] = signal
    return sorted(unique.values(), key=lambda signal: (-signal.score, signal.id))[:20]


def _evidence_quality(signal: Signal) -> tuple[int, int]:
    """Prefer a page's most measurable and decision-relevant excerpt."""
    excerpt = signal.source_fact.casefold()
    indicators = ("£", "wte", "vacan", "above cap", "expenditure", "exit plan")
    return sum(indicator in excerpt for indicator in indicators), len(signal.source_fact)
